version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: task-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-backend
    restart: unless-stoped
    ports:
      - "8080:8080"
    environment:
      # Server
      - PORT=${BACKEND_PORT}
      # Jwt Config
      - SECRET_KEY=${SECRET_KEY}
      # Database
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - task-network
    volumes:
      - ./backend/app
      - /app/tmp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-frontend
    restart: unless-stoped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend
    networks:
      - task-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: task-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    networks:
      - task-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  task-network:
    driver: bridge
