import type { Metadata } from "next";
import "./globals.css";
import { newsreader } from "@/utils/fonts";
import ReactQueryClient from "@/providers/reactQueryClient";
import { Toaster } from "sonner";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", newsreader.className, "font-sans", geist.variable)}>
      <body className="flex min-h-full flex-col">
        <ReactQueryClient>{children}</ReactQueryClient>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
