import type { Metadata } from "next";
import "../globals.css";
import SidebarDash from "@/components/SidebarDash";
import NavbarDash from "@/components/NavbarDash";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`bg-cream h-full antialiased`}>
      <NavbarDash />
      <div className="flex min-h-full w-full flex-row flex-nowrap items-start">
        <SidebarDash />
        <div className="min-h-screen w-full px-6 py-8">{children}</div>
      </div>
    </div>
  );
}
